### ISSUE TITLE
jar包中的class在反编译时，依然存在bug，也不知是因为作者心胸狭窄，接受不了建议，还是因为作者是bug爱好者呢？

### ISSUE THREAD

**Issue by viogel4** [work-helper/class-decompile-intellij#4]

**Comment by mrdear** [comment]
小伙子，有话好好说，不要一上来就人身攻击。。。

不合并你的，因为PR质量太差了，随便给你几张图，建议先补补，不要在热血的年纪做无脑的事情。

最后你的PR我不会合并的，建议fork后自己开一个吧。



![image](https://user-images.githubusercontent.com/13889883/102703004-57cc2b00-42a4-11eb-9ac0-3a9cbfc8e559.png)

![image](https://user-images.githubusercontent.com/13889883/102702996-353a1200-42a4-11eb-8cbb-75ef2aa7672f.png)
